services:
  - type: web
    name: order-tracker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2"
    envVars:
      # We will store the Google Credentials JSON as a single string environment variable
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
